### ISSUE TITLE
Installation fails on WIndows 10

### ISSUE THREAD

**Issue by capcionista** [LinusU/fs-xattr#15]
Hi, I have problems installing fs-xattr. I would be grateful if you could help me out.

C:\Users\User1\.atom\packages\node_modules\fs-xattr>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  async.cc
  error.cc
  sync.cc
  util.cc
  xattr.cc
..\src\async.cc(7): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "s
ys/xattr.h": No such file or directory [C:\Users\User1\.atom\packages\node_modules\fs
-xattr\build\xattr.vcxproj]
..\src\error.cc(76): error C2065: 'ENOTBLK': nichtdeklarierter Bezeichner [C:\Users\h
erte\.atom\packages\node_modules\fs-xattr\build\xattr.vcxproj]
..\src\error.cc(76): error C2051: case-Ausdruck ist keine Konstante [C:\Users\User1\.
atom\packages\node_modules\fs-xattr\build\xattr.vcxproj]
..\src\sync.cc(7): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "sy
s/xattr.h": No such file or directory [C:\Users\User1\.atom\packages\node_modules\fs-
xattr\build\xattr.vcxproj]
c:\users\User1\.atom\packages\node_modules\fs-xattr\node_modules\nan\nan_new.h(214):
warning C4267: 'Argument': Konvertierung von 'size_t' nach 'int', Datenverlust möglic
h (..\src\util.cc) [C:\Users\User1\.atom\packages\node_modules\fs-xattr\build\xattr.v
cxproj]
          ..\src\util.cc(14): Siehe Verweis auf die Instanziierung der gerade kompili
  erten Funktions-template "v8::MaybeLocal<v8::String> Nan::New<v8::String,const char
  *,size_t>(A0,A1)".
          with
          [
              A0=const char *
  ,            A1=size_t
          ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User1\.atom\packages\node_modules\fs-xattr
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "fs-xattr"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! fs-xattr@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-xattr@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fs-xattr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fs-xattr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fs-xattr
npm ERR! There is likely additional logging output above.

**Comment by LinusU** [comment]
Sorry in the delay on responding to this. Windows doesn't have support for extended attributes, and thus I don't see this library ever gaining Windows support. Possibly in the future if they add it to their next file system implementation.

I just wrote some more about this here: nodejs/node#7469

> I took a stab not to long ago on getting windows support into the fs-xattr package, but it ended with me abandoning it since there is no clear equivalent to extended attributes on Windows. NTFS has something called [Alternative Data Stream](https://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_.28ADS.29) which could potentially be used to store similar data, but it felt to shoehorned to put it in the same package since the use case is often wildly different.

> As such I don't think that it makes sense to have this in Node core since it's very platform specific, and because you probably want two different APIs, one for ADS and one for extended attributes.

**Comment by LinusU** [comment]
Maybe this could work after all, track progress here: #16

**Comment by iffy** [comment]
@LinusU could a first step be to have `npm install fs-xattr` not fail on Linux/Windows?

**Comment by iffy** [comment]
Nm, I will make it an optionalDependency.  Sorry for the noise.
