### ISSUE TITLE
Can not install - error with python version

### ISSUE THREAD

**Issue by AndreevskiAleksandar** [LinusU/fs-xattr#21]
I have this issue when trying to install trough npm.

>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-
> gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.2, which is not supported by gyp.
> gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
> gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:14)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:443:9
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
> gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
> gyp ERR! stack     at emitOne (events.js:96:13)
> gyp ERR! stack     at Socket.emit (events.js:188:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\Projects\electron-media-player\node_modules\fs-xattr
> gyp ERR! node -v v6.9.1
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok

I am using Windows 8.1.
Any suggestions on this one?

**Comment by LinusU** [comment]
I think that you need to install Python 2.x...

**Comment by LinusU** [comment]
As I said, you need to have Python 2.x for the current Node.js native addon build chain. Please feel free to reopen if you have any other issues
