### ISSUE TITLE
Use N-API instead of NAN

### ISSUE THREAD

**Issue by sindresorhus** [LinusU/fs-xattr#25]
The N-API is now stable and will be 100% backward compatible in the future. Using it will mean less work for you and make it compatible with any future Node.js version.

https://nodejs.org/api/n-api.html

N-API requires Node.js 8, but I think it's fine to target that as this module is used on the users' computer and not in a server environment.

**Comment by LinusU** [comment]
Yeah, would be nice. Since it's going to be a breaking change anyhow, we should switch to promises as well 👍

**Comment by LinusU** [comment]
Forgot this was open 😄 but I implemented this in #29 🎉

**Comment by LinusU** [comment]
Fixed in 0.3.0 🚢
