### ISSUE TITLE
Convert buffer to JSON

### ISSUE THREAD

**Issue by brettz9** [LinusU/fs-xattr#32]
Any chance you might support the likes of this:

`xattr -px com.apple.LaunchServices.OpenWith <file-name> | xxd -r -p | plutil -p -`

...which gives a result like this for me, when my `<file-name>` is one for which I have set to a custom "Open with" in "Get info":

```
{
  "bundleidentifier" => "me.brett-zamir.demos.jsedit"
  "path" => "/Users/brett/Desktop/Edit JavaScript.app"
  "version" => 0
}
```

...and converting it to a JSON format?

**Comment by LinusU** [comment]
This is outside of the scope for this package, but it seems like this package can parse the bplist format for you: https://github.com/joeferner/node-bplist-parser

Should be easy to read the attribute as a buffer with this module, and then pass it to that module for parsing. Good luck!

**Comment by brettz9** [comment]
Great, much appreciated, thanks!
