### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by unreadablewxy** [LinusU/fs-xattr#35]
Hi, this library is pretty neat. Have you given any thoughts to licensing? Technically, all projects currently using this library are doing so without a license and violating your copyright.

I'm not saying what to pick, just that it would the more legally conscious folks like myself less hesitant to incorporate this into our projects if this is clarified.

**Comment by unreadablewxy** [comment]
Nevermind, saw it in package.json

**Comment by LinusU** [comment]
I've added a license file as well ✔️  https://github.com/LinusU/fs-xattr/commit/a002d5cfde6ce5f55a6ac7e129b4706253a2a996
