### ISSUE TITLE
Build failing on FreeBSD 13.1

### ISSUE THREAD

**Issue by duncan-bayne** [LinusU/fs-xattr#45]
I'm trying to build the latest fs-xattr source, but it's failing because it can't find Python:

```
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
gyp ERR! stack     at exithandler (node:child_process:410:5)
gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:422:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! stack     at onErrorNT (node:internal/child_process:485:16)
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
gyp ERR! System FreeBSD 13.1-RELEASE-p6
```

I have uploaded the full log: [2023-03-21T02_48_42_689Z-debug-0.log](https://github.com/LinusU/fs-xattr/files/11024623/2023-03-21T02_48_42_689Z-debug-0.log)

This might be because the default Python binary is `python3.9`.

```
$ which python3.9
/usr/local/bin/python3.9
```

**Comment by LinusU** [comment]
> node-gyp/lib/find-python.js:330:47

I think that this is a problem with `node-gyp`, would you be able to file an issue with them as well?

**Comment by duncan-bayne** [comment]
Ah!  I went there to do that, but it looks like they've already made provision for it.  So e.g. in `node-gyp` you can do:

`export PYTHON=$(which python3.9)`

However, this led to two _further_ issues:

1. Failing `node-gyp` tests, and
2. Continued failure to install `fs-xattr` - it seems that the `PYTHON` environment variable is ignored during installation `¯\_(ツ)_/¯`

If I create a `/usr/local/bin/python3` symlink _then_ it starts working, only to fail with #40 again (this time on FreeBSD 13.1).

So:

1. I've Re-opened #40.
2. I will file a bug on `node-gyp` about disregarding `PYTHON` during installation.
3. I'll close this bug.

**Comment by duncan-bayne** [comment]
Ah I was wrong - I hadn't set PYTHON correctly.  With that set it installs as expected, but fails on #40.
